## NumPy

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/econ2025-de/blob/main/01-Python/01-03-Numpy.ipynb)

In der vorherigen Lektion haben wir uns mit Listen beschäftigt. Diese sind sehr flexibel, aber auch sehr langsam. Mit kleinen Listen werden wir das nicht merken, aber wenn wir mit großen Datenmengen arbeiten, dann können lange Laufzeiten zum Problem werden. 

NumPy (Numerical Python) ist ein Paket, das viele Funktionen enthält, die für die Arbeit mit großen Datenmengen geeignet sind.

NumPy-Arrays sind sehr ähnlich zu Listen, aber sie haben einige zusätzliche Eigenschaften. Zum Beispiel können wir mit NumPy-Arrays rechnen. Wenn wir zwei NumPy-Arrays addieren, dann werden die Elemente an der gleichen Stelle addiert. Diese Syntax ist sehr intuitiv und einfach zu lesen.


In [19]:
# Importieren der Bibliothek NumPy

import numpy as np

# Erstellen eines Arrays

# 1D Array

x = np.array([1, 2, 3, 4, 5])
x

y = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(x)
print(y)

[1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


In [20]:
z1 = x + 1 
z2 = x + y
print("x + 1 =", z1)
print("x + y =", z2)

x + 1 = [2 3 4 5 6]
x + y = [1.1 2.2 3.3 4.4 5.5]


Dasselbe funktioniert mit Python-Listen nicht. Wenn wir zwei Listen addieren, dann werden die Elemente an der gleichen Stelle nicht addiert, sondern die Listen werden aneinander gehängt.

In [21]:
x_list = [2, 7, 5, 2]
y_list = [1, 1, 1, 1]
x_plus_y_list = x_list + y_list
x_plus_y_list

[2, 7, 5, 2, 1, 1, 1, 1]

In [22]:
# x_list + 1

NumPy-Arrays haben auch einige Methoden, die wir mit Listen nicht haben. Zum Beispiel können wir die Summe aller Elemente eines Arrays berechnen.

In [23]:
# Summe der Elemente
x.sum()

np.int64(15)

In [24]:
# Durchschnitt der Elemente (Arithmetischer Mittelwert)

x.mean()

np.float64(3.0)

In [25]:
# Standardabweichung
x.std()

np.float64(1.4142135623730951)

In [26]:
# Minimum
x.min()

np.int64(1)

In [27]:
# Maximum
x.max()

np.int64(5)

### Slicing

Wir können auch auf die Elemente eines Arrays zugreifen, indem wir einen Index angeben. Der Index beginnt bei 0.

In [28]:
z = np.array(["a", "b", "c", "d", "e"])

In [29]:
# Das erste Element
z[0]

np.str_('a')

In [30]:
# Alle Elemente bis zur Indexposition 2 (exklusive)
# Achten Sie darauf, dass der Index 0-basiert ist und daher das dritte Element ist eine Indexposition 2 hat
z[:2]

array(['a', 'b'], dtype='<U1')

In [31]:
z[1:3]

array(['b', 'c'], dtype='<U1')

### Arrays und Listen Zuweisung

Eine zugängige Erläuterung, wie Werte im Speicher des Rechners gespeichert werden, finden Sie in [hier](https://mvschamanth.medium.com/inside-python-are-variables-memory-references-a7522808be93).

In [25]:
z[1] = "x"
z

array(['a', 'x', 'c', 'd', 'e'], dtype='<U1')

In [26]:
z1 = z

In [27]:
z[0] = "X"

In [28]:
z1

array(['X', 'x', 'c', 'd', 'e'], dtype='<U1')

In [29]:
z1 == z

array([ True,  True,  True,  True,  True])